### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by fragsalat** [krojew/tracing-elastic-apm#13]
Hey there,

seems like I'm to dump to configure the lib properly. For me it seems like there is an infinite loop as the ApmClient is sending a network request for closed spans and hyper is opening new spans for each network request. Is it only me observing this? I also would like to see in the readme an example which integrates with the formatter example from the tracing lib.

Here is my dump code
```rust

#[tracing::instrument]
pub async fn run_traced_test_task() {
    info!("Some task");
    thread::sleep(Duration::from_secs(10));
    info!("Another log");
}

#[tokio::main]
async fn main() {
    let apm_layer = tracing_elastic_apm::new_layer(
        "monitor-helper".to_string(),
        Config::new("http://127.0.0.1:8200".to_string()),
    )
    .expect("APM Layer to be created");

    tracing_subscriber::registry().with(apm_layer).init();

    info!("Started!");

    let handle = tokio::spawn(async {
        std::thread::sleep(Duration::from_secs(5));
        run_traced_test_task().await;
    });

    tokio::try_join!(handle).unwrap();

    std::thread::sleep(Duration::from_secs(5));
    info!("Goodbye");
}
```

**Comment by krojew** [comment]
I can look at this after about 2w, unfortunately.

**Comment by krojew** [comment]
Can you confirm everything is working fine on current master?
