### ISSUE TITLE
No event are reported except for `ERROR`

### ISSUE THREAD

**Issue by woshilapin** [krojew/tracing-elastic-apm#4]
I tried to instrument my code and use this library. I was not able to make it works until I started looking directly into the code of the library and stumble on [that line](https://github.com/krojew/tracing-elastic-apm/blob/9b646f0f930a18bc68ad960f092e414ee78eb804/src/layer.rs#L109).

It happens that the code I was running was never reporting on `ERROR` level. I'm wondering why only `ERROR` events are reported and not the other type of `Level`. Or maybe I missed something else?

**Comment by krojew** [comment]
APM normally supports only 4 types of data: transactions, spans, errors and metrics. These map to the corresponding concepts in the `tracing` ecosystem: span without a parent, span with a parent, error event and nothing. As you can see, APM does not support any other event type than error, hence this check.

**Comment by woshilapin** [comment]
Oh, so it's a limitation from APM, I see. Thank you for the precision, I'm still pretty new to APM.
