### ISSUE TITLE
Authorization header for ApiKey authentication is wrongly formatted

### ISSUE THREAD

**Issue by DamianoChini** [krojew/tracing-elastic-apm#7]
## Bug description
It is not possible to authenticate to the APM Server via ApiKey.

### Details
The HTTP Authorization header for authenticating via ApiKey should be in the form:
`Authorization: ApiKey <base64_encoded_credentials `
see: [Elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html#security-api-create-api-key-example) (I could not find APM Server specific doc for the ApiKey authentication).

Here instead the `ApiKey` identifier is also base64 encoded. So the authentication does not work.
https://github.com/krojew/tracing-elastic-apm/blob/7634b123307311401b8b982810f316f04b6bf6e2/src/apm_client.rs#L75

**Comment by ufoscout** [comment]
@krojew 
We are having the same issue. Would you please perform a new release containing this fix?
