### ISSUE TITLE
tracing-elastic-apm does not work without a global subscriber

### ISSUE THREAD

**Issue by ufoscout** [krojew/tracing-elastic-apm#9]
The `tracing-elastic-apm` layer does nothing if used with a default subscriber. E.g.:
```rust

let stdout_layer = ...;
let another_layer = ...;
let another_another_layer = ...;

let tracing_elastic_apm_layer = tracing_elastic_apm::new_layer(
    "ServiceName".to_string(),
    tracing_elastic_apm::Config::new("APM address".to_string())
)?;

// The order of registration of the layers has no impact on this bug
    let subscriber = tracing_subscriber::registry()
        .with(stdout_layer)
        .with(another_layer)
        .with(another_another_layer)
        .with(tracing_elastic_apm_layer);

// Using a default subscriber all layers work as expected except 
// the tracing_elastic_apm_layer that does NOT work at all
let _guard = tracing::subscriber::set_default(subscriber);

// It works as expected if we use a global subscriber instead:
// tracing::subscriber::set_global_default(subscriber).unwrap()
```
Any idea why?

**Comment by krojew** [comment]
After registering layers, you should call `init()`.

```
tracing_subscriber::registry()
        .with(stdout_layer)
        .with(another_layer)
        .with(another_another_layer)
        .with(tracing_elastic_apm_layer)
        .init();       // you should call init here
```

**Comment by ufoscout** [comment]
@krojew 
Calling `init()` sets the subscriber as the global default one which is exactly what I don't want to do. This issue is indeed about the fact that the `tracing-elastic-apm` works when the subscriber is global but it does not work when using a default non-global one:
```
let _guard = tracing::subscriber::set_default(subscriber);
```

**Comment by krojew** [comment]
What other layers you found working in such case?

**Comment by ufoscout** [comment]
This is a small snippet of our real code:
```rust

        // Log to a file
        let file_appender = tracing_appender::rolling::never(dir, filename);
        let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);
        let file_layer = Layer::new().with_ansi(false).with_writer(non_blocking);

        // Log to stdout
        let (non_blocking, stdout_guard) = tracing_appender::non_blocking(std::io::stdout());
        let stdout_layer = Layer::new().with_ansi(false).with_writer(non_blocking);

    let subscriber = tracing_subscriber::registry()
        .with(env_filter) // EnvFilter
        .with(file_layer) 
        .with(apm_layer)
        .with(stdout_layer);
```

everything works except the `apm_layer`.

**Comment by krojew** [comment]
Can you try calling `set_default()` directly on `subscriber`, rather than `tracing::subscriber::set_default(subscriber)`?

**Comment by ufoscout** [comment]
Tried, the issue is still present.

**Comment by krojew** [comment]
After some investigation, it looks like https://docs.rs/tracing-subscriber/0.2.20/tracing_subscriber/fmt/struct.Layer.html works a bit differently than this crate. It's hard to tell if this is the reason, or if any of those two behaviors is wrong. If you use `with_writer`, everything that happens to spans gets converted to events and written to given writer (https://docs.rs/tracing-subscriber/0.2.20/src/tracing_subscriber/fmt/fmt_layer.rs.html#587). `tracing-elastic-apm`, on the other hand, distinguishes between events and spans, and sends span data only when a span gets closed.

Therefore we're left with some open questions:
* Is this the reason for this behavior?
* Is `fmt::Layer` implementation actually correct?

It's possible you found either a bug or undocumented behavior in `tracing-subscriber`. I'm not sure if there's anything I can do in this case.

**Comment by ufoscout** [comment]
@krojew 
After in-depth investigations, we found that the issue is not in this crate but, somehow, in [tracing-actix-web](https://github.com/LukeMathWalker/tracing-actix-web) that does not log the HTTP request info when the subscriber is not global.
